name: 주식 분석 파이프라인 수동 테스트

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 23 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. 내 코드 저장소 가져오기
      uses: actions/checkout@v4

    - name: 2. 파이썬 환경 세팅하기
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 

    - name: 3. 필요한 라이브러리 설치하기
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 4. 파이썬 코드(main.py) 실행하기
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: python main.py
